
POST http://127.0.0.1:8000/accounts/register/
Content-Type: application/json

{
    "username":"pam",
    "password":"12341234",
    "email":"alex@gmail.com",
    "phone":"93234xxxxx"
}

###
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
    "username" : "pam",
    "password" : "12341235"
}

###
GET http://127.0.0.1:8000/accounts/profile/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NTE2OTUyLCJpYXQiOjE3Njk1MTY2NTIsImp0aSI6IjU2YjhmNTJiZmM4ZDQwMTE5ZTA1MWM3ZTczMzk2YTVjIiwidXNlcl9pZCI6IjE5In0.gXNUHYAlSirfd3cadQBPqVHVUUXds2B8ajnIStaHbLI

###
GET http://127.0.0.1:8000/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NjE0NDQyLCJpYXQiOjE3Njk2MTQxNDIsImp0aSI6ImJhMzVhMzdhNTE4NjQyZTliOThlYjBjMTM1Zjc1M2E1IiwidXNlcl9pZCI6IjE5In0.QsYrriizglPqOLWupx86miQYODy20iQQTWm8Mj-CvNU