# Generated by Django 6.0.1 on 2026-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_parent_category_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.CharField(max_length=27),
        ),
    ]
