# Generated by Django 6.0.1 on 2026-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'Upi'), ('card', 'Crd'), ('net-banking', 'Nbn'), ('wallet', 'Wlt')], default='upi', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pn'), ('success', 'Sc'), ('failed', 'Fl')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pn'), ('paid', 'Pd'), ('shipped', 'Sh'), ('delivered', 'Dl'), ('cancelled', 'Cn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
